# Project configuration for external/public documentation
## This is the main configuration file that contains most of your site settings
site_name: "Knowledge Base"
site_description: Knowledge Base for Sitetracker's products and services
site_author: SiteTracker
site_url: https://sitetracker.com/kb

# Repository (disabled)
# repo_name: sitetracker/docs
# repo_url: https://github.com/sitetracker/docs
# edit_uri: edit/trunk/docs/

# Copyright
copyright: Copyright &copy; 2023 SiteTracker, Inc.

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#101820"
      accent: "#00B2A9"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#101820"
      accent: "#00B2A9"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: "Source Code Pro"
  favicon: assets/favicon.svg
  logo: assets/logo.svg
  features:
    - navigation.tracking
    # Removed navigation.tabs to keep navigation only in the left sidebar
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # - navigation.expand  # Removed to allow collapsible sections
    - navigation.path
    # Enhanced navigation features
    - navigation.instant
    - navigation.prune   # Automatically hide nested sections
    - toc.follow         # Automatically follow table of contents
    # Collapsible sections with arrow indicators
    - navigation.collapsible
    # Content features
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    # Section index pages
    - navigation.indexes
    # UI features
    - header.autohide
    # Search features with centered search bar
    - search.highlight
    - search.share
    - search.suggest
    # Enable print function 
    - content.action.print
  
  # Set the site name to be shown in browser tabs while keeping navigation clean
  site_name: " "
  site_url: https://sitetracker.com/kb

# Configure extra settings
extra:
  generator: false  # Remove the "Made with Material for MkDocs" footer text
  # Set a fixed title for all pages
  title: "Knowledge Base"
  # Algolia DocSearch Configuration (Uncomment and add your credentials when available)
  # search:
  #   language: en
  #   provider: algolia
  #   separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  # algolia:
  #   application_id: !ENV ALGOLIA_APP_ID
  #   api_key: !ENV ALGOLIA_API_KEY  # Search-only API key
  #   index_name: !ENV ALGOLIA_INDEX_NAME
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sitetrackerinc
      name: Sitetracker on X/Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sitetracker/
      name: Sitetracker on LinkedIn
  version:
    provider: mike

# Enable additional plugins
plugins:
  - search
  - tags
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  # Table of contents settings
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 2
  # Math support
  - pymdownx.arithmatex:
      generic: true
  # Various text formatting extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: sitetracker
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  # Code blocks and fences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/fix-material-errors.js
  - assets/javascripts/error-handler.js
  - assets/javascripts/utils.js
  - assets/javascripts/config/env-config.js
  - assets/javascripts/config-loader.js
  - assets/javascripts/internal-content-handler.js
  - assets/javascripts/extra.js
  - assets/javascripts/algolia-search.js
  - assets/javascripts/auto-link.js

# Page tree
nav:
  - Home: home/index.md
    - Getting Started: home/getting-started.md
    - Installation: home/installation.md
    - Configuration: home/configuration.md
    - Customizations: customizations.md
  - Usage: usage/index.md
    - User Guide: usage/user-guide.md
    - API Overview: usage/api-overview.md
  - Features: features/index.md
    - One-Click Sharing: features/one-click-sharing.md
    - JIRA Integration: features/jira-integration.md
  - Examples: getting-started/index.md
    - Content Format Example: getting-started/content-format-example.md
    - Mixed Content Example: getting-started/mixed-content-example.md
  - Release Notes: release-notes/index.md
    - Latest Release (March 2025): release-notes/latest.md
    - Changelog: CHANGELOG.md