name: Preview Documentation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin pymdown-extensions
      
      - name: Build documentation
        run: |
          # Build public documentation
          mkdocs build -f mkdocs.yml -d site
          
          # Check if PR branch is from internal team member to build internal docs
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            # Build internal documentation
            mkdocs build -f mkdocs.internal.yml -d site/internal
          fi
      
      - name: Deploy preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site --json
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
      - name: Get Netlify deploy URL
        id: netlify
        run: |
          URL=$(cat .netlify/state.json | jq -r '.siteUrl')
          echo "PREVIEW_URL=$URL" >> $GITHUB_ENV
      
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = process.env.PREVIEW_URL;
            const body = `📚 Documentation preview is ready!\n\nYou can view it here: ${previewUrl}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
